# Generated by Django 5.0 on 2024-01-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmodel',
            options={'verbose_name_plural': 'Brands'},
        ),
    ]
