# Generated by Django 5.0 on 2024-01-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_alter_warrantymodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodle',
            old_name='brandbrand',
            new_name='brand',
        ),
    ]
